### PR TITLE
feat(options): added --prefix option

### PR DESCRIPTION
**Pull request by dannycoates**
Hi! I'm a new `nps` user and I love it! I added this feature for myself but maybe it'd be useful to others.

**What**:

This adds a `prefix` option to prepend a string to the start of each script name in the cli

**Why**:

I wanted to be able to do something like this:

_cli_
```sh
npm test unit functional
```

_package-scripts.js_
```js
module.exports = {
  scripts: {
    test: {
      unit: 'mocha ./tests',
      functional: 'intern'
    }
  }
}
```

_package.json_
```json
{
  "scripts": {
    "test": "nps --prefix=test"
  }
}
```

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by dannycoates** [comment]
I don't think the `default` case is working here. I'll push an update soon

**Comment by sezna** [comment]
@dannycoates is this ready for review now? Sorry, I didn't see you updated it after the last comment!

**Comment by dannycoates** [comment]
@sezna yes, it's ready, thanks!

**Comment by sezna** [comment]
Looks good to me, sorry about the delay!

**Pull request merged**
