### PR TITLE
 feat: support .npsrc file for cli config

### PR DESCRIPTION
**Pull request by effervescentia**
**What**:

Adding support for a `.npsrc` or `.npsrc.json` configuration file to provide the `require` and `config` options to `nps`.

**Why**:

To simplify setups which require a preloaded module such as `@babel/register` especially when used with `nps-utils`.

_Before and After_
Screenshot 2019-06-16 at 5 05 54 PM

**How**:

Used `find-up` to search for a `.npsrc` or `.npsrc.json` file, parse it, filter out unwanted keys, then pass the result to `yargs.config()` to use as the default config when parsing `process.argv`.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by effervescentia** [comment]
@danecando @florianloechle @kevjin sorry to put you on blast, but you were the last 3 to make contributions to this project. Could I bother one of you to take a look and sign off on my changes?

**Comment by effervescentia** [comment]
@kentcdodds how do you want to move forward with this? Is there someone you can reach out to review this? If not, what should we do to proceed?

**Comment by kentcdodds** [comment]
Would you be willing to take over maintenance of this project? That would involve me transferring the repository and npm package to you and separating myself completely from `nps`. I just don't have the bandwidth to maintain it anymore :-(

**Comment by sezna** [comment]
This looks good to me, and I think it is a good addition.

**Comment by cursedcoder** [comment]
Would be nice to update https://github.com/sezna/nps/issues/215

**Pull request merged**
